#!/usr/bin/env bash
# redirect to 301

sudo apt-get update
sudo apt-get -y install nginx

sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://collinskoch.me permanent;" /etc/nginx/sites-available/default
service nginx reload
service nginx start
