#!/usr/bin/env bash
# Configure Nginx to include a custom header in its HTTP response on web-01 and web-02.
# The custom HTTP header should be named X-Served-By.
# The value of X-Served-By should be the hostname of the Nginx server.
sudo apt-get update
sudo apt-get -y install nginx

# Configure the firewall to allow requests through port 80 for Nginx HTTP.
sudo ufw allow 'Nginx HTTP'

# Create the necessary directory structure for the web content.
sudo mkdir -p /var/www/html

# Adjust permissions to enable easy file creation in this directory.
sudo chmod -R 755 /var/www

# Create the index page with the content "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 error page.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure a redirect for a single page (/redirect_me) and add a header to display the hostname.
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.collinskoch.me permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure the server to display the custom 404 error page.
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the Nginx web server to apply the updated settings.
sudo service nginx restart
