#!/usr/bin/env bash
# configure HAproxy
# Make sure that HAProxy can be managed using int

# Install the HAproxy on lb-01 server.
echo -e "Updating...\n"

function install() {
	command -v "$1" &> /dev/null


	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy

echo -e "\nSetting up.\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s
frontend eaglevision-tech-frontend
    bind *:80
    default_backend eaglevision-tech-backend
backend eaglevision-tech-backend
    balance roundrobin
    server 244043-web-01 100.25.13.237 check
    server 244043-web-02 35.175.129.126 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
