#!/usr/bin/env bash
# This script that displays a list of currently running processes.


process_info=$(ps -ef --forest --no-headers)

echo "PID    PPID   USER         COMMAND"
echo "----------------------------------"

echo "$process_info" | while read -r line; do
  pid=$(echo "$line" | awk '{print $2}')
  ppid=$(echo "$line" | awk '{print $3}')
  user=$(echo "$line" | awk '{print $1}')
  command=$(echo "$line" | awk '{$1=$2=$3=""; print $0}' | sed -e 's/^\s*//')

  printf "%-6s %-6s %-12s %s\n" "$pid" "$ppid" "$user" "$command"
done
