#!/usr/bin/env bash
# This script creates my process

pid_file="/var/run/my_process.pid"

start_process() {
  if [ -f "$pid_file" ]; then
    echo "manage_my_process is already running."
  else
    nohup ./manage_my_process >/dev/null 2>&1 &
    echo $! > "$pid_file"
    echo "manage_my_process started."
  fi
}

stop_process() {
  if [ -f "$pid_file" ]; then
    pid=$(cat "$pid_file")
    rm "$pid_file"
    kill "$pid"
    echo "manage_my_process stopped."
  else
    echo "manage_my_process is not running."
  fi
}

restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted."
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
