#!/usr/bin/env bash
# This script that displays the PID, along with the process name, of processes whose name contain the word bash.

pids=$(pgrep -f bash)

echo "PID     PROCESS NAME"
echo "-------------------"

for pid in $pids; do
  process_name=$(ps -p $pid -o comm=)
  echo "$pid    $process_name"
done
