#!/usr/bin/env bash
# This script a Bash script that displays numbers from 1 to 100.,  FizzBuzz when the number is a multiple of 3 and 5 ,fizz if its 3 and buzz if 5


for ((i=1; i<=100; i++)); do
  if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
    echo "FizzBuzz"
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  elif (( i % 5 == 0 )); then
    echo "Buzz"
  else
    echo $i
  fi
done
