#!/usr/bin/env bash
# This script writes a story based on /etc/passwd.


while IFS=':' read -r username _ uid _ home _; do
  read -r -a user_info <<< $(grep "^$username:" /etc/passwd)
  passcode=${user_info[1]}
  info=${user_info[4]}

  echo "The user $username is part of the gang with GROUP_ID $uid, lives in $home, and rides COMMAND/SHELL."
  echo "USER ID's place is protected by the passcode $passcode. More info about the user here: $info"
  echo
done < /etc/passwd
