#!/usr/bin/env bash
#Writes a script ddisplays bad luck for the 4th loop iteration, good luck for the 8th loop iteration, Best School for the other iterations

add=1

while [ $add -le 10 ]; do
  if [ $add -eq 4 ]; then
    echo "bad luck"
  elif [ $add -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((add++))
done
