#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

saa=0

while [ $saa -le 12 ]
do
  echo "Hour: $saa"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( saa++ ))
done
